#Welcome to our Lab practice!

This lab is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below. 

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.





## Import the package and rename it as np

In [2]:
# your code is here
import numpy as np

## Array Creation

### Task: Create a numpy array from a list of integers

In [3]:
# your code is here
np.array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

### Task: Create a numpy array of size 6, filled with zeros

In [5]:
# your code is here
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

###Task: Create a numpy array of size 6, filled with ones

In [6]:
# your code is here
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

###Task: Create a numpy array with values from 0 to 10

In [7]:
# your code is here
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [8]:
# your code is here
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

###Task: Create a numpy matrix of 3*2 integers, filled with ones

In [9]:
# your code is here
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

###Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [11]:
# your code is here
np.random.randint(0, 11, (3, 2))

array([[1, 0],
       [6, 7],
       [6, 1]])

###Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [12]:
# your code is here
np.random.rand(100, 2)

array([[0.36061417, 0.22813467],
       [0.90858271, 0.06632447],
       [0.17538382, 0.49078585],
       [0.86421808, 0.31081037],
       [0.49499906, 0.93020243],
       [0.57569841, 0.55963419],
       [0.44938363, 0.41855375],
       [0.16894612, 0.840603  ],
       [0.36224653, 0.01594224],
       [0.17176141, 0.62660537],
       [0.38089541, 0.23688689],
       [0.18066243, 0.15954909],
       [0.28627271, 0.57608839],
       [0.7385182 , 0.83031395],
       [0.70726099, 0.86681804],
       [0.98746667, 0.70781307],
       [0.54568984, 0.45179902],
       [0.80257985, 0.92630997],
       [0.41970888, 0.44901697],
       [0.66668145, 0.75503874],
       [0.80188253, 0.16925749],
       [0.85265048, 0.4277868 ],
       [0.32766787, 0.37003288],
       [0.05703688, 0.51176182],
       [0.08459137, 0.59760241],
       [0.34439264, 0.54063487],
       [0.77231046, 0.59656847],
       [0.04882562, 0.74956658],
       [0.02268274, 0.26121662],
       [0.10787445, 0.79296257],
       [0.

###Task: Create a numpy matrix of 2 * 3 * 4, filled with integers from 1 to 24.

In [14]:
# your code is here
np.arange(1, 25).reshape(2, 3, 4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [15]:
# your code is here
X = np.array([1, 2, 3, 4, 5])

### Task: Show the first element of X

In [16]:
# your code is here
X[0]

1

### Task: Show the last element of X

In [17]:
# your code is here
X[-1]

5

### Task: Show the first 3 elements of X

In [18]:
# your code is here
X[:3]

array([1, 2, 3])

###Task: Show the last 3 elements of X

In [19]:
# your code is here
X[-3:]

array([3, 4, 5])

###Task: Show the elements of X whose index is odd (1, 3, 5, ...)

In [22]:
# your code is here
X[1::2]

array([2, 4])

###Task: Show the elements of X except the last one

In [23]:
# your code is here
X[:-1]

array([1, 2, 3, 4])

### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [26]:
# your code is here
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###Task: Show the first row of X

In [27]:
# your code is here
X[0]

array([0, 1, 2, 3])

###Task: Show the first column of X

In [28]:
# your code is here
X[:,0]

array([0, 4, 8])

###Task: Show the first element of the first row of X

In [30]:
# your code is here
X[0, 0]

0

###Task: Show the last row of X

In [31]:
# your code is here
X[-1]

array([ 8,  9, 10, 11])

###Task: Show the last column of X

In [32]:
# your code is here
X[:,-1]

array([ 3,  7, 11])

###Task: Show the last element of the last row of X

In [33]:
# your code is here
X[-1, -1]

11

###Task: Show all the rows except the last row of X

In [35]:
# your code is here
X[:-1,:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

###Task: Show all the columns except the last column of X

In [36]:
# your code is here
X[:,:-1]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

### Task: Show the first two elements of the first two rows

In [37]:
# your code is here
X[:2,:2]

array([[0, 1],
       [4, 5]])

## Array Statistics

###Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [41]:
# your code is here
X = np.arange(10)
print(X)
print(X.sum())
print(X.mean())
print(X.std())
print(X.var())
print(X.max())
print(X.min())

[0 1 2 3 4 5 6 7 8 9]
45
4.5
2.8722813232690143
8.25
9
0


###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [42]:
# your code is here
X = np.arange(12).reshape(3,4)
print(X[0])
print(X[0].sum())
print(X[0].mean())
print(X[0].std())
print(X[0].var())
print(X[0].max())
print(X[0].min())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
1.5
1.118033988749895
1.25
3
0


###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st column of it.

In [45]:
# your code is here
print(X[:,0])
print(X[:,0].sum())
print(X[:,0].mean())
print(X[:,0].std())
print(X[:,0].var())
print(X[:,0].max())
print(X[:,0].min())

[0 4 8]
12
4.0
3.265986323710904
10.666666666666666
8
0
