In [2]:
#Import numpy
import numpy as np

#### Basic Arrays ####

In [9]:
# Create a numpy array and assign it to a variable. Check the type.
a = np.array([0,1,2,3])
type(a)

numpy.ndarray

In [10]:
# We can check the shape of the array using the .shape method

a.shape

(4,)

In [12]:
# Indexing works the same as in lists.

print(a[0], a[2], a[3])

0 2 3


In [13]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [14]:
a[-1]

3

In [15]:
a[-4]

0

In [16]:
a[-5]

IndexError: index -5 is out of bounds for axis 0 with size 4

In [17]:
# We can also slice the same way as a list

a[0:]

array([0, 1, 2, 3])

In [18]:
a[1:3]

array([1, 2])

In [19]:
a[:2]

array([0, 1])

In [20]:
a[:-1]

array([0, 1, 2])

In [21]:
a[-2:]

array([2, 3])

In [22]:
a[::2]

array([0, 2])

In [23]:
a[1::2]

array([1, 3])

#### Array Types ####

In [3]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([0.0, 0.1, 0.2, 0.3])

In [11]:
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float64')

In [8]:
c = np.array([0, 1.1, 2, 3.8], dtype = float)

In [13]:
c.dtype

dtype('float64')

In [17]:
d = np.array([0, 1.1, 2, 3.8], dtype = int)

In [18]:
d.dtype

dtype('int32')

#### Dimensions and Shapes ####

In [19]:
a = np.array([0, 1, 2, 3, 4])

In [20]:
a.shape

(5,)

In [23]:
# Matrix Array
A = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

In [24]:
A.shape

(3, 4)

In [27]:
# 3 Dimensional Matrix

B = np.array([
    [
        [0, 1],
        [2, 3],
        [4, 5]
    ],
    [
        [6, 7],
        [8, 9],
        [10, 11]
    ]
])

In [28]:
B.shape

(2, 3, 2)

In [30]:
# Check number of dimensions
B.ndim

3

In [31]:
B.size

12

### Indexing and Slicing Matrices ###

In [32]:
A = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

In [33]:
A.shape

(2, 4)

In [34]:
A[0]

array([0, 1, 2, 3])

In [35]:
A[1]

array([4, 5, 6, 7])

In [36]:
A[:0]

array([], shape=(0, 4), dtype=int32)

In [37]:
A[:1]

array([[0, 1, 2, 3]])

In [38]:
# Column
A[:,0]

array([0, 4])

In [39]:
# Column
A[:,3]

array([3, 7])

In [41]:
# Indexing for one item
A[0,0]

0

In [42]:
A[1,3]

7

In [45]:
# Getting specific columns
A[:,1:3]

array([[1, 2],
       [5, 6]])