In [2]:
#Import numpy
import numpy as np

#### Basic Arrays ####

In [9]:
# Create a numpy array and assign it to a variable. Check the type.
a = np.array([0,1,2,3])
type(a)

numpy.ndarray

In [10]:
# We can check the shape of the array using the .shape method

a.shape

(4,)

In [12]:
# Indexing works the same as in lists.

print(a[0], a[2], a[3])

0 2 3


In [13]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [14]:
a[-1]

3

In [15]:
a[-4]

0

In [16]:
a[-5]

IndexError: index -5 is out of bounds for axis 0 with size 4

In [17]:
# We can also slice the same way as a list

a[0:]

array([0, 1, 2, 3])

In [18]:
a[1:3]

array([1, 2])

In [19]:
a[:2]

array([0, 1])

In [20]:
a[:-1]

array([0, 1, 2])

In [21]:
a[-2:]

array([2, 3])

In [22]:
a[::2]

array([0, 2])

In [23]:
a[1::2]

array([1, 3])

#### Array Types ####

In [3]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([0.0, 0.1, 0.2, 0.3])

In [11]:
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float64')

In [8]:
c = np.array([0, 1.1, 2, 3.8], dtype = float)

In [13]:
c.dtype

dtype('float64')

In [17]:
d = np.array([0, 1.1, 2, 3.8], dtype = int)

In [18]:
d.dtype

dtype('int32')

#### Dimensions and Shapes ####

In [19]:
a = np.array([0, 1, 2, 3, 4])

In [20]:
a.shape

(5,)

In [23]:
# Matrix Array
A = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

In [24]:
A.shape

(3, 4)

In [27]:
# 3 Dimensional Matrix

B = np.array([
    [
        [0, 1],
        [2, 3],
        [4, 5]
    ],
    [
        [6, 7],
        [8, 9],
        [10, 11]
    ]
])

In [28]:
B.shape

(2, 3, 2)

In [30]:
# Check number of dimensions
B.ndim

3

In [31]:
B.size

12

### Indexing and Slicing Matrices ###

In [32]:
A = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

In [33]:
A.shape

(2, 4)

In [34]:
A[0]

array([0, 1, 2, 3])

In [35]:
A[1]

array([4, 5, 6, 7])

In [36]:
A[:0]

array([], shape=(0, 4), dtype=int32)

In [37]:
A[:1]

array([[0, 1, 2, 3]])

In [38]:
# Column
A[:,0]

array([0, 4])

In [39]:
# Column
A[:,3]

array([3, 7])

In [41]:
# Indexing for one item
A[0,0]

0

In [42]:
A[1,3]

7

In [45]:
# Getting specific columns
A[:,1:3]

array([[1, 2],
       [5, 6]])

In [46]:
A[0] = np.array([8, 9, 10, 11])

In [47]:
A[1] = 98

In [48]:
A

array([[ 8,  9, 10, 11],
       [98, 98, 98, 98]])

### Statistics ###

In [56]:
a = np.array([0, 1, 2, 4])

In [57]:
a

array([0, 1, 2, 4])

In [58]:
a.sum()

7

In [59]:
a.mean()

1.75

In [60]:
# Standard Deviation
a.std()

1.479019945774904

In [61]:
# Variance
a.var()

2.1875

In [62]:
a.max()

4

In [63]:
a.min()

0

In [64]:
A = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

In [65]:
A.sum()

66

In [66]:
A.mean()

5.5

In [67]:
A.std()

3.452052529534663

In [68]:
A.var()

11.916666666666666

In [70]:
A.max()

11

In [71]:
# Sum by columns
A.sum(axis = 0)

array([12, 15, 18, 21])

In [72]:
# Sum by row
A.sum(axis=1)

array([ 6, 22, 38])

In [74]:
A.mean(axis=0)

array([4., 5., 6., 7.])

In [75]:
A.max(axis=1)

array([ 3,  7, 11])

### Linear Algebra ###

In [76]:
A = np.array([
    [0, 1, 1],
    [3, 4, 5]
])

B = np.array([
    [6, 7, 8],
    [9, 10, 11]
])

In [77]:
A

array([[0, 1, 1],
       [3, 4, 5]])

In [78]:
B

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
A + B

array([[ 6,  8,  9],
       [12, 14, 16]])

In [80]:
A - B

array([[-6, -6, -7],
       [-6, -6, -6]])

In [83]:
# This is pairwise NOT dot product
A * B

array([[ 0,  7,  8],
       [27, 40, 55]])

In [84]:
# Transpose
B.T

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [86]:
# Dot product of A times B

A @ (B.T)

array([[ 15,  21],
       [ 86, 122]])

In [87]:
# Dot product of B times A

A.T @ B

array([[27, 30, 33],
       [42, 47, 52],
       [51, 57, 63]])

### Numpy Functions ###

In [88]:
# A Range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [90]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [92]:
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [94]:
# Reshape (rows, columns)
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [95]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
# Numpy includes random library, random.randint gives you numbers from parameter a to parameter b (non inclisive)
# and and the last parameter in brackets is the number of items in the array
np.random.randint(0, 10, (10))

array([5, 8, 8, 0, 7, 7, 2, 5, 5, 8])

In [100]:
# We can use the size parameter tupple to define the size
np.random.randint(0, 10, (5, 2))

array([[1, 8],
       [7, 4],
       [8, 5],
       [8, 9],
       [1, 7]])

In [102]:
# We can use rand to create arrays of random floats
np.random.rand(2, 4)

array([[0.57907426, 0.3303214 , 0.29919517, 0.59542361],
       [0.2709337 , 0.25689956, 0.78385519, 0.46847308]])

In [103]:
# Normal distibutions using mean, standard deviation and size
np.random.normal(0, 0.1, (10))

array([ 0.10482563, -0.12569196, -0.11415866,  0.03032855, -0.20248652,
       -0.14699037, -0.16160489,  0.02344318,  0.00529328, -0.06754788])

In [104]:
np.random.normal(0, 0.1, (2, 5))

array([[ 0.13320919,  0.04452089,  0.10414176,  0.00573352,  0.11583856],
       [ 0.03463124,  0.00365625, -0.01541498, -0.00228715, -0.07502784]])

In [105]:
# Uniform distribution
np.random.uniform(0, 1, (3, 4))

array([[0.53289798, 0.72544964, 0.51828561, 0.08533493],
       [0.70599739, 0.69021921, 0.03391969, 0.0902479 ],
       [0.85532932, 0.8678459 , 0.67194691, 0.1245772 ]])

In [106]:
a = np.random.uniform(0, 1, (2, 5))

In [107]:
a

array([[0.28168597, 0.9516853 , 0.10232497, 0.67889712, 0.08302534],
       [0.15726375, 0.50451855, 0.50306587, 0.49682044, 0.4298496 ]])

In [108]:
# Sorting arrays
np.sort(a)

array([[0.08302534, 0.10232497, 0.28168597, 0.67889712, 0.9516853 ],
       [0.15726375, 0.4298496 , 0.49682044, 0.50306587, 0.50451855]])

In [109]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [110]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [112]:
np.ones((2, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])