In [1]:
#Import numpy
import numpy as np

#### Basic Arrays ####

In [9]:
# Create a numpy array and assign it to a variable. Check the type.
a = np.array([0,1,2,3])
type(a)

numpy.ndarray

In [10]:
# We can check the shape of the array using the .shape method

a.shape

(4,)

In [12]:
# Indexing works the same as in lists.

print(a[0], a[2], a[3])

0 2 3


In [13]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [14]:
a[-1]

3

In [15]:
a[-4]

0

In [16]:
a[-5]

IndexError: index -5 is out of bounds for axis 0 with size 4

In [17]:
# We can also slice the same way as a list

a[0:]

array([0, 1, 2, 3])

In [18]:
a[1:3]

array([1, 2])

In [19]:
a[:2]

array([0, 1])

In [20]:
a[:-1]

array([0, 1, 2])

In [21]:
a[-2:]

array([2, 3])

In [22]:
a[::2]

array([0, 2])

In [23]:
a[1::2]

array([1, 3])